apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: object-detection-app-secure
spec:
  params:
    - default: object-detection-app
      name: APP_NAME
      type: string
    - default: 'https://github.com/jstakun/object-detection-app.git'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: object-detection-app
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: 14-ubi8
      name: VERSION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
        - name: ENV_VARS
          value: ['NPM_MIRROR=http://nexus.apps-infra.svc:8081/repository/npm-proxy/']
      runAfter:
        - sca-dependency-analysis
      taskRef:
        kind: ClusterTask
        name: s2i-nodejs
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: >-
            oc rollout restart deploy/$(params.APP_NAME);oc rollout status
            deploy/$(params.APP_NAME) -w
      runAfter:
        - skopeo-copy
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE_NAME)
        - name: destImageURL
          value: 'docker://quay.io/jstakun/$(params.IMAGE_NAME)'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: workspace
    - name: sca-dependency-analysis
      params:
        - name: manifest-file-path
          value: package.json
        - name: output-file-path
          value: redhat-codeready-dependency-analysis-report.json
        - name: pkg-installation-directory-path
          value: /
        - name: image
          value: 'quay.io/jstakun/crda-nodejs:latest'
      runAfter:
        - pre-task-setup
      taskRef:
        kind: Task
        name: redhat-codeready-dependency-analysis
      workspaces:
        - name: output
          workspace: workspace
    - name: pre-task-setup
      params:
        - name: file_url
          value: 'file://package.json'
        - name: manifest-file-path
          value: package.json
        - name: pkg-installation-directory-path
          value: .
        - name: image
          value: quay.io/jstakun/crda-nodejs
        - name: type
          value: nodejs
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: pre-task-setup
      workspaces:
        - name: output
          workspace: workspace
  workspaces:
    - name: workspace
