apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mlapp
spec:
  params:
    - default: object-detection-rest
      name: APP_NAME
      type: string
    - default: 'https://github.com/jstakun/object-detection-rest.git'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: object-detection-rest
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: deploy
      params:
        - name: SCRIPT
          value: oc rollout restart deploy/$(params.APP_NAME);oc rollout status
            deploy/$(params.APP_NAME) -w
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: build
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE_NAME):latest
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:23fb7971ea6ac4aaaaa1139473a602df0df19222a3b5a76b551b2b9ddd92e927
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: >-
            --squash      
            --build-arg PIP_INDEX_URL='' --build-arg
            PIP_TRUSTED_HOST=nexus.apps-infra.svc
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
