apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pre-task-setup
spec:
  params:
    - name: file_url
      type: string
    - default: requirements.txt
      name: manifest-file-path
      type: string
    - default: site-package
      name: pkg-installation-directory-path
      type: string
    - default: 'ghcr.io/fabric8-analytics/crda-python:3.7'
      name: image
      type: string
    - default: python
      type: string
      name: type 
  steps:
    - image: $(params.image)
      name: pre-task-setup
      resources: {}
      script: |
        #!/bin/sh

        mkdir -p $(params.pkg-installation-directory-path)
        #curl $(params.file_url) --output $(params.manifest-file-path)
        if [ "$(params.type)" = "python" ]; then
            pip3 install --trusted-host=nexus.apps-infra.svc \ 
            --index-url=http://nexus.apps-infra.svc:8081/repository/pypi-proxy/simple/ \
            --target=$(params.pkg-installation-directory-path) \
            -r $(params.manifest-file-path) --upgrade
        elif [ "$(params.type)" = "nodejs" ]; then
            npm set registry http://nexus.apps-infra.svc:8081/repository/npm-proxy/
            npm install $(params.pkg-installation-directory-path)
        else
            echo "Invalid language " $(params.type)
        fi                                                                                        
      workingDir: $(workspaces.output.path)
  workspaces:
    - name: output
