---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: notebook-test
  namespace: apps-kafka
  labels:
    strimzi.io/cluster: ai-cluster
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1048576          
  partitions: 1
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: objects
  namespace: apps-kafka
  labels:
    strimzi.io/cluster: ai-cluster  
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1048576          
  partitions: 1
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: images
  namespace: apps-kafka
  labels:
    strimzi.io/cluster: ai-cluster  
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1048576
  partitions: 1
  replicas: 3
