---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: notebook-test
  namespace: apps-kafka
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1048576          
  partitions: 1
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: objects
  namespace: apps-kafka
spec:
  config:
    retention.ms: 3600000
    segment.bytes: 1048576          
  partitions: 1
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: images
  namespace: apps-kafka
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 3
