apiVersion: v1
kind: Secret
metadata:
  name: object-detection-kafka
  labels:
    app: object-detection
    app.kubernetes.io/component: object-detection
    app.kubernetes.io/instance: object-detection
    app.kubernetes.io/part-of: object-detection
data:
stringData:
  KAFKA_BOOTSTRAP_SERVER: ai-cluster-kafka-bootstrap.apps-kafka.svc.cluster.local:9092
  KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
  KAFKA_SASL_MECHANISM: SCRAM-SHA-512
  KAFKA_USERNAME: ai-user
  #oc get secret ai-user -n apps-kafka -o go-template --template="{{.data.password|base64decode}}"
  KAFKA_PASSWORD: <Kafka User SA password>
  KAFKA_TOPIC_IMAGES: images
  KAFKA_TOPIC_OBJECTS: objects
